[DataList]
#------------------------------------------------
Datas = ["JA","Hirogin","Momiji","HiroginSouzoku","JASouzoku","Tuka"]

[ParList]
#------------------------------------------------
Name = ["日付列","金額列","変換対象列","日付列名","入金列名","出金列名","残高列名","自動仕訳基準列名"]
日付列 = "HidukeColNo"
金額列 = "MoneyCol"
変換対象列 = "ChangeTextCol"
日付列名 = "HidukeColName"
入金列名 = "NyuName"
出金列名 = "SyutuName"
残高列名 = "ZanName"
自動仕訳基準列名 = "Henkan"

[JA]
#------------------------------------------------
HidukeColNo = 1
MoneyCol = [4,5,6]
ChangeTextCol = [2]
ColumnName = ["日付","摘要","摘要2","出金","入金","残高"]
HidukeColName = "日付"
NyuName = "入金"
SyutuName = "出金"
ZanName = "残高"
Henkan = "摘要"
ChangeText = [
    "ATM"
    ]

[Hirogin]
#------------------------------------------------
HidukeColNo = 1
MoneyCol = [3,4,5]
ColumnName = ["No","日付","預金番号1","預金番号2","摘要","出金","入金","残高"]
HidukeColName = "日付"
NyuName = "入金"
SyutuName = "出金"
ZanName = "残高"
Henkan = "摘要"
ChangeText = [
    "トヨタファイナンス(カブ",
    "ヒロシマギンコウDC",
    "オリコ",
    "ハートフォードセイメイホケ",
    "カゴメ",
    "イトウハム",
    "トウシンブンパイキン",
    "トウシンコウニュウ",
    "UC(アオヤマキャピタル)",
    "クレジット",
    "キュウヨ",
    "フリコミ",
    "リソク",
    "ハイトウキン",
    "フリカエ",
    "テイキ"
    ]

[Momiji]
#------------------------------------------------
HidukeColNo = 2
MoneyCol = [6,7,8]
ChangeTextCol = [5]
ColumnName = ["No","日付","預金番号1","預金番号2","摘要","出金","入金","残高"]
HidukeColName = "日付"
NyuName = "入金"
SyutuName = "出金"
ZanName = "残高"
Henkan = "摘要"
ChangeText = [
    "トヨタファイナンス(カブ",
    "ヒロシマギンコウDC",
    "オリコ",
    "ハートフォードセイメイホケ",
    "カゴメ",
    "イトウハム",
    "トウシンブンパイキン",
    "トウシンコウニュウ",
    "UC(アオヤマキャピタル)",
    "クレジット",
    "キュウヨ",
    "フリコミ",
    "リソク",
    "ハイトウキン",
    "フリカエ",
    "テイキ"
    ]

[HiroginSouzoku]
#------------------------------------------------
HidukeColNo = 1
MoneyCol = [6,7,8]
ChangeTextCol = [4,9]
ColumnName = ["日付","No","無題","摘要","種類","出金","入金","残高","摘要2"]
HidukeColName = "日付"
NyuName = "入金"
SyutuName = "出金"
ZanName = "残高"
Henkan = "摘要"
ChangeText = [
    "トヨタファイナンス(カブ",
    "ヒロシマギンコウDC",
    "オリコ",
    "ハートフォードセイメイホケ",
    "カゴメ",
    "イトウハム",
    "トウシンブンパイキン",
    "トウシンコウニュウ",
    "UC(アオヤマキャピタル)",
    "クレジット",
    "キュウヨ",
    "フリコミ",
    "リソク",
    "ハイトウキン",
    "フリカエ",
    "テイキ"
    ]


[JASouzoku]
#------------------------------------------------
HidukeColNo = 1
MoneyCol = [7,8]
ChangeTextCol = [6,9,10]
ColumnName = ["取引日","取引種別","取引区分","摘要","ネット情報","貸借","取引金額","残高","媒体区分","コメント"]
HidukeColName = "日付"
NyuName = "貸借"
SyutuName = "取引金額"
ZanName = "残高"
Henkan = "摘要"
ChangeText = [
    "KDDI料金",
    "呉上下水道",
    "サンヨウガス",
    "#借",
    "通帳"
    ]

[Tuka]
#------------------------------------------------
HidukeColNo = 1
MoneyCol = [3,4,5]
ChangeTextCol = [1]
ColumnName = ["品名","数量","単価","金額","摘要"]
HidukeColName = "日付"
NyuName = "単価"
SyutuName = "金額"
ZanName = "摘要"
Henkan = "品名"
ChangeText = [
    "トヨタファイナンス(カブ",
    "ヒロシマギンコウDC",
    "オリコ",
    "ハートフォードセイメイホケ",
    "カゴメ",
    "イトウハム",
    "トウシンブンパイキン",
    "トウシンコウニュウ",
    "UC(アオヤマキャピタル)",
    "クレジット",
    "キュウヨ",
    "フリコミ",
    "リソク",
    "ハイトウキン",
    "フリカエ",
    "テイキ"
    ]