[ListSetting]
Columns = [
    "列番号",
    "列番号2",
    "列番号3",
]
Index = [
    "日付列",
    "金額列",
]
"日付列" = [
    "1",
]
"金額列" = [
    "3",
    "4",
    "5",
]

[ColumnSetting]
Columns = [
    "列名",
]
Index = [
    "1",
    "2",
    "3",
    "4",
]
1 = [
    "日付",
]
2 = [
    "入金",
]
3 = [
    "出金",
]
4 = [
    "残高",
]

[OCR_ListSetting]
Columns = [
    "列番号",
    "列番号2",
    "列番号3",
]
Index = [
    "日付列",
    "金額列",
]
"日付列" = [
    "1",
]
"金額列" = [
    "3",
    "4",
    "5",
]

[OCR_ColumnSetting]
Columns = "['列名']"
Index = "['1', '2', '3', '4']"
1 = [
    "日付",
]
2 = [
    "入金",
]
3 = [
    "出金",
]
4 = [
    "残高",
]

[1869_1page_ListSetting]
Columns = [
    "列番号",
    "列番号2",
    "列番号3",
]
Index = [
    "日付列",
    "金額列",
]
"日付列" = [
    "1",
]
"金額列" = [
    "3",
    "4",
    "5",
]

[1869_1page_ColumnSetting]
Columns = "['列名']"
Index = "['1', '2', '3', '4', '5']"
1 = [
    "日付",
]
2 = [
    "摘要",
]
3 = [
    "出金",
]
4 = [
    "入金",
]
5 = [
    "残高",
]

[1869_2page_ListSetting]
Columns = "['列番号', '列番号2', '列番号3']"
Index = "['日付列', '金額列']"
"日付列" = [
    "1",
]
"金額列" = [
    "3",
    "4",
    "5",
]

[1869_2page_ColumnSetting]
Columns = "['列名']"
Index = "['1', '2', '3', '4', 5]"
1 = [
    "日付",
]
2 = [
    "摘要",
]
3 = [
    "入金",
]
4 = [
    "出金",
]
5 = [
    "残高",
]
